### PR TITLE
added main.js and firebase.js

### PR DESCRIPTION
**Pull request by Hodal66**

### CODE REVIEW

**Comment by Hodal66** [comment]
Any One can help to solve this error

**Review by PrinceNiyonshuti — APPROVED** [review]
great work

**Comment by PrinceNiyonshuti** [comment]
> Any One can help to solve this error

which error ?

**Comment by arthurjunior250** [comment]
if it's possible you can add screenshots and descriptions

**Comment by Hodal66** [comment]
am trying to make authontication but it does't work

**Comment by Hodal66** [comment]
They are steel giving me error in console

**Comment by Hodal66** [comment]
> 

brother i have issue about connectiong with firebase and how to test if it work propery

**Review by PrinceNiyonshuti — APPROVED** [review]
good progress

**Comment by Hodal66** [comment]
**What does this PR do?**
• Implements login section with firebase  
   -implement legister section with firebase
**Description of Task to be completed?**
-User can be able to send the message to the administrator  
-User should now log into dashboad page
**How should this be manually tested?**
• Clone the repo
• checkout to branch "contactmebranch"
• Run npm install to install modules
• Run npm run build to start the development server
What are the relevant Pivotal Tracker/trello stories?
• link to my pivotal tracker    https://trello.com/b/O0UciNNa/mybrand
Screenshots (if appropriate)
Questions:
-I'm having a blocker on subscribing and unsubscribing you can help me to fix it.

**Pull request merged**
